const APIEndpoints = {
  KrphAllActivities: {
    GetMasterDataBindingList: "FGMS/GetMasterDataBinding",
    GetLocationMasterDataBindingList: "FGMS/GetLocationMasterDataBinding",
    GetDistrictByStateDataList: "FGMS/GetDistrictByState",
    GetBankByDistrictDataList: "FGMS/GetBankByDistrict",
    GetBranchByBankANDDistrictDataList: "FGMS/GetBranchByBankANDDistrict",
    GetSubDistrictByStateANDDistrictDataList: "FGMS/GetSubDistrictByStateANDDistrict",
    GetVillageListBYSubDistrictAndDistrictDataList: "FGMS/GetVillageListBYSubDistrictAndDistrict",
    CheckFarmerByMobileNumber: "FGMS/CheckFarmerByMobileNumber",
    CheckFarmerByAadharNumber: "FGMS/CheckFarmerByAadharNumber",
    CheckFarmerByAccountNumber: "FGMS/CheckFarmerByAccountNumber",
    CheckFarmerByPolicy: "FGMS/GetPolicyByVillageID",
    GetAppInsuranceDetails: "FGMS/GetInsuranceDetail",
    GetFarmerPolicyDetail: "FGMS/GetFarmerPolicyDetail",
    AddSupportTicket: "FGMS/AddSupportTicket",
    GenerateSupportTicket: "FGMS/GenerateSupportTicket",
    SendSMSToFarmer: "FGMS/SendSMSToFarmer",
    SearchPolicy: "FGMS/SearchPolicy",
    CheckFarmer: "FGMS/CheckFarmerByDb",
    GetClaimDetail: "FGMS/GetClaimDetail",
    GetLocationHierarchy: "FGMS/GetLocationHierarchy",
    GetLevel3: "FGMS/GetLevel3",
    GetLevel4: "FGMS/GetLevel4",
    GetLevel5: "FGMS/GetLevel5",
    GetLevel6: "FGMS/GetLevel6",
    GetLevel7: "FGMS/GetLevel7",
    UploadDocument: "FGMS/UploadDocument",
    FarmerCallingHistory: "FGMS/FarmerCallingHistory",
    AddKRPHSupportTicket: "FGMS/AddKRPHSupportTicket",
    KrphFarmerCallingHistory: "FGMS/KrphFarmerCallingHistory",
    CheckKRPHFarmerByMobileNumber: "FGMS/CheckKRPHFarmerByMobileNumber",
    KRPHFarmerSelect: "FGMS/KRPHFarmerSelect",
  },
};

export default APIEndpoints;
